# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\scenario_browser\ui_files\search_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScenSearchPanel(object):
    def setupUi(self, ScenSearchPanel):
        ScenSearchPanel.setObjectName("ScenSearchPanel")
        ScenSearchPanel.resize(311, 356)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScenSearchPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_pattern = QtWidgets.QLineEdit(ScenSearchPanel)
        self.text_pattern.setObjectName("text_pattern")
        self.horizontalLayout.addWidget(self.text_pattern)
        self.button_search = QtWidgets.QPushButton(ScenSearchPanel)
        self.button_search.setObjectName("button_search")
        self.horizontalLayout.addWidget(self.button_search)
        self.button_cancel = QtWidgets.QPushButton(ScenSearchPanel)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_search_results = QtWidgets.QListWidget(ScenSearchPanel)
        self.list_search_results.setObjectName("list_search_results")
        self.verticalLayout.addWidget(self.list_search_results)

        self.retranslateUi(ScenSearchPanel)
        QtCore.QMetaObject.connectSlotsByName(ScenSearchPanel)

    def retranslateUi(self, ScenSearchPanel):
        _translate = QtCore.QCoreApplication.translate
        ScenSearchPanel.setWindowTitle(_translate("ScenSearchPanel", "Form"))
        self.text_pattern.setToolTip(_translate("ScenSearchPanel", "Enter search pattern (regexp)"))
        self.text_pattern.setStatusTip(_translate("ScenSearchPanel", "Enter search pattern (regexp)"))
        self.button_search.setToolTip(_translate("ScenSearchPanel", "Search the objects in the current scenario"))
        self.button_search.setStatusTip(_translate("ScenSearchPanel", "Search the objects in the current scenario"))
        self.button_search.setText(_translate("ScenSearchPanel", "Search"))
        self.button_cancel.setToolTip(_translate("ScenSearchPanel", "Cancel the current search"))
        self.button_cancel.setStatusTip(_translate("ScenSearchPanel", "Cancel the current search"))
        self.button_cancel.setText(_translate("ScenSearchPanel", "Cancel"))

