# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\sim\main\ui_files\run_setup_parts.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunSetupPartsDialog(object):
    def setupUi(self, RunSetupPartsDialog):
        RunSetupPartsDialog.setObjectName("RunSetupPartsDialog")
        RunSetupPartsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        RunSetupPartsDialog.resize(638, 589)
        RunSetupPartsDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(RunSetupPartsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_area = QtWidgets.QWidget(RunSetupPartsDialog)
        self.main_area.setObjectName("main_area")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_area)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructions = QtWidgets.QWidget(self.main_area)
        self.instructions.setObjectName("instructions")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.instructions)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line1 = QtWidgets.QLabel(self.instructions)
        self.line1.setObjectName("line1")
        self.verticalLayout_3.addWidget(self.line1)
        self.line2 = QtWidgets.QLabel(self.instructions)
        self.line2.setObjectName("line2")
        self.verticalLayout_3.addWidget(self.line2)
        self.verticalLayout.addWidget(self.instructions)
        self.arguments = QtWidgets.QTreeWidget(self.main_area)
        self.arguments.setColumnCount(4)
        self.arguments.setObjectName("arguments")
        self.arguments.headerItem().setText(0, "1")
        self.arguments.headerItem().setText(1, "2")
        self.arguments.headerItem().setText(2, "3")
        self.arguments.headerItem().setText(3, "4")
        self.arguments.header().setDefaultSectionSize(150)
        self.verticalLayout.addWidget(self.arguments)
        self.verticalLayout_2.addWidget(self.main_area)
        self.button_area = QtWidgets.QWidget(RunSetupPartsDialog)
        self.button_area.setObjectName("button_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_area)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_button = QtWidgets.QPushButton(self.button_area)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout.addWidget(self.load_button)
        self.save_button = QtWidgets.QPushButton(self.button_area)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.button_box_ok_cancel = QtWidgets.QDialogButtonBox(self.button_area)
        self.button_box_ok_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.button_box_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box_ok_cancel.setObjectName("button_box_ok_cancel")
        self.horizontalLayout.addWidget(self.button_box_ok_cancel)
        self.verticalLayout_2.addWidget(self.button_area)

        self.retranslateUi(RunSetupPartsDialog)
        self.button_box_ok_cancel.accepted.connect(RunSetupPartsDialog.accept) # type: ignore
        self.button_box_ok_cancel.rejected.connect(RunSetupPartsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RunSetupPartsDialog)

    def retranslateUi(self, RunSetupPartsDialog):
        _translate = QtCore.QCoreApplication.translate
        RunSetupPartsDialog.setWindowTitle(_translate("RunSetupPartsDialog", "Run Setup Parts"))
        self.line1.setText(_translate("RunSetupPartsDialog", "Enter a value for each call argument of each Setup part. The parts are shown in execution priority."))
        self.line2.setText(_translate("RunSetupPartsDialog", "Click OK to run the parts with the given argument values, or Cancel to abandon this operation."))
        self.load_button.setText(_translate("RunSetupPartsDialog", "Load..."))
        self.save_button.setText(_translate("RunSetupPartsDialog", "Save..."))

