# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\part_editors\ui_files\actor_part_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActorPartEditorWidget(object):
    def setupUi(self, ActorPartEditorWidget):
        ActorPartEditorWidget.setObjectName("ActorPartEditorWidget")
        ActorPartEditorWidget.resize(520, 449)
        self.verticalLayout = QtWidgets.QVBoxLayout(ActorPartEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.use_default_image = QtWidgets.QCheckBox(ActorPartEditorWidget)
        self.use_default_image.setObjectName("use_default_image")
        self.verticalLayout.addWidget(self.use_default_image)
        self.img_editor_widget = ImgEditorWidget(ActorPartEditorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.img_editor_widget.sizePolicy().hasHeightForWidth())
        self.img_editor_widget.setSizePolicy(sizePolicy)
        self.img_editor_widget.setObjectName("img_editor_widget")
        self.verticalLayout.addWidget(self.img_editor_widget)

        self.retranslateUi(ActorPartEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(ActorPartEditorWidget)

    def retranslateUi(self, ActorPartEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        ActorPartEditorWidget.setWindowTitle(_translate("ActorPartEditorWidget", "Form"))
        self.use_default_image.setText(_translate("ActorPartEditorWidget", "Use default image"))
from .img_editor import ImgEditorWidget
