# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\part_editors\ui_files\clock_part_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClockPartEditorWidget(object):
    def setupUi(self, ClockPartEditorWidget):
        ClockPartEditorWidget.setObjectName("ClockPartEditorWidget")
        ClockPartEditorWidget.resize(278, 337)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClockPartEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ClockPartEditorWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(53, 0))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(53, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ClockPartEditorWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ticksEdit = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ticksEdit.setDecimals(11)
        self.ticksEdit.setMinimum(-999999999.0)
        self.ticksEdit.setMaximum(999999999.0)
        self.ticksEdit.setObjectName("ticksEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ticksEdit)
        spacerItem = QtWidgets.QSpacerItem(53, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(ClockPartEditorWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.daysEdit = QtWidgets.QSpinBox(self.groupBox_3)
        self.daysEdit.setMaximum(999999999)
        self.daysEdit.setObjectName("daysEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.daysEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.hoursEdit = QtWidgets.QSpinBox(self.groupBox_3)
        self.hoursEdit.setMaximum(999999999)
        self.hoursEdit.setObjectName("hoursEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hoursEdit)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.minutesEdit = QtWidgets.QSpinBox(self.groupBox_3)
        self.minutesEdit.setMaximum(999999999)
        self.minutesEdit.setObjectName("minutesEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minutesEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.secondsEdit = QtWidgets.QSpinBox(self.groupBox_3)
        self.secondsEdit.setMaximum(999999999)
        self.secondsEdit.setObjectName("secondsEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.secondsEdit)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(ClockPartEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(ClockPartEditorWidget)

    def retranslateUi(self, ClockPartEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("ClockPartEditorWidget", "Date/Time"))
        self.label.setText(_translate("ClockPartEditorWidget", "Date:"))
        self.dateEdit.setDisplayFormat(_translate("ClockPartEditorWidget", "yyyy/MM/dd"))
        self.label_2.setText(_translate("ClockPartEditorWidget", "Time:"))
        self.timeEdit.setDisplayFormat(_translate("ClockPartEditorWidget", "hh:mm:ss"))
        self.groupBox_2.setTitle(_translate("ClockPartEditorWidget", "Ticks"))
        self.groupBox_3.setTitle(_translate("ClockPartEditorWidget", "Tick Period"))
        self.label_4.setText(_translate("ClockPartEditorWidget", "Days:"))
        self.label_5.setText(_translate("ClockPartEditorWidget", "Hours:"))
        self.label_6.setText(_translate("ClockPartEditorWidget", "Minutes:"))
        self.label_7.setText(_translate("ClockPartEditorWidget", "Seconds:"))

