# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\part_editors\ui_files\file_part_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilePartEditorWidget(object):
    def setupUi(self, FilePartEditorWidget):
        FilePartEditorWidget.setObjectName("FilePartEditorWidget")
        FilePartEditorWidget.resize(680, 104)
        self.file_path_linedit = QtWidgets.QLineEdit(FilePartEditorWidget)
        self.file_path_linedit.setGeometry(QtCore.QRect(50, 20, 491, 20))
        self.file_path_linedit.setObjectName("file_path_linedit")
        self.file_path_button = QtWidgets.QPushButton(FilePartEditorWidget)
        self.file_path_button.setGeometry(QtCore.QRect(550, 20, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_path_button.sizePolicy().hasHeightForWidth())
        self.file_path_button.setSizePolicy(sizePolicy)
        self.file_path_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.file_path_button.setObjectName("file_path_button")
        self.label = QtWidgets.QLabel(FilePartEditorWidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 51, 23))
        self.label.setObjectName("label")
        self.folder_path_button = QtWidgets.QPushButton(FilePartEditorWidget)
        self.folder_path_button.setGeometry(QtCore.QRect(600, 20, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.folder_path_button.sizePolicy().hasHeightForWidth())
        self.folder_path_button.setSizePolicy(sizePolicy)
        self.folder_path_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.folder_path_button.setObjectName("folder_path_button")
        self.file_part_relative_to_scenario_folder_checkbox = QtWidgets.QCheckBox(FilePartEditorWidget)
        self.file_part_relative_to_scenario_folder_checkbox.setGeometry(QtCore.QRect(0, 60, 171, 17))
        self.file_part_relative_to_scenario_folder_checkbox.setObjectName("file_part_relative_to_scenario_folder_checkbox")

        self.retranslateUi(FilePartEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(FilePartEditorWidget)

    def retranslateUi(self, FilePartEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        FilePartEditorWidget.setWindowTitle(_translate("FilePartEditorWidget", "Edit File Part"))
        self.file_path_linedit.setPlaceholderText(_translate("FilePartEditorWidget", "Select file or folder"))
        self.file_path_button.setText(_translate("FilePartEditorWidget", "File"))
        self.label.setText(_translate("FilePartEditorWidget", "File Path:"))
        self.folder_path_button.setText(_translate("FilePartEditorWidget", "Folder"))
        self.file_part_relative_to_scenario_folder_checkbox.setText(_translate("FilePartEditorWidget", "Relative to Scenario Folder"))

