# Form implementation generated from reading ui file 'origame\gui\part_editors\ui_files\info_part_editor.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InfoPartEditorWidget(object):
    def setupUi(self, InfoPartEditorWidget):
        InfoPartEditorWidget.setObjectName("InfoPartEditorWidget")
        InfoPartEditorWidget.resize(559, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(InfoPartEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_text = QtWidgets.QTextEdit(parent=InfoPartEditorWidget)
        self.info_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.info_text.setObjectName("info_text")
        self.verticalLayout.addWidget(self.info_text)

        self.retranslateUi(InfoPartEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(InfoPartEditorWidget)

    def retranslateUi(self, InfoPartEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        InfoPartEditorWidget.setWindowTitle(_translate("InfoPartEditorWidget", "Form"))
