# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\part_editors\ui_files\img_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImgEditorWidget(object):
    def setupUi(self, ImgEditorWidget):
        ImgEditorWidget.setObjectName("ImgEditorWidget")
        ImgEditorWidget.resize(368, 290)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ImgEditorWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_groupbox = QtWidgets.QGroupBox(ImgEditorWidget)
        self.image_groupbox.setObjectName("image_groupbox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.image_groupbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.image_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 237))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_2.addWidget(self.image_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.widget = QtWidgets.QWidget(self.image_groupbox)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select = QtWidgets.QPushButton(self.widget)
        self.select.setObjectName("select")
        self.verticalLayout.addWidget(self.select)
        self.rotate_left = QtWidgets.QPushButton(self.widget)
        self.rotate_left.setObjectName("rotate_left")
        self.verticalLayout.addWidget(self.rotate_left)
        self.rotate_right = QtWidgets.QPushButton(self.widget)
        self.rotate_right.setObjectName("rotate_right")
        self.verticalLayout.addWidget(self.rotate_right)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.image_groupbox)

        self.retranslateUi(ImgEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(ImgEditorWidget)

    def retranslateUi(self, ImgEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        ImgEditorWidget.setWindowTitle(_translate("ImgEditorWidget", "Form"))
        self.image_groupbox.setTitle(_translate("ImgEditorWidget", "Image"))
        self.image_label.setText(_translate("ImgEditorWidget", "Image place holder"))
        self.select.setText(_translate("ImgEditorWidget", "Select"))
        self.rotate_left.setText(_translate("ImgEditorWidget", "Rotate Left"))
        self.rotate_right.setText(_translate("ImgEditorWidget", "Rotate Right"))

