# Form implementation generated from reading ui file 'origame\gui\part_editors\ui_files\import_object_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportObjectDialog(object):
    def setupUi(self, ImportObjectDialog):
        ImportObjectDialog.setObjectName("ImportObjectDialog")
        ImportObjectDialog.resize(387, 150)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ImportObjectDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 110, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(parent=ImportObjectDialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 371, 38))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.source_module = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_module.sizePolicy().hasHeightForWidth())
        self.source_module.setSizePolicy(sizePolicy)
        self.source_module.setObjectName("source_module")
        self.horizontalLayout_3.addWidget(self.source_module)
        self.module_location_edit = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_location_edit.sizePolicy().hasHeightForWidth())
        self.module_location_edit.setSizePolicy(sizePolicy)
        self.module_location_edit.setObjectName("module_location_edit")
        self.horizontalLayout_3.addWidget(self.module_location_edit)
        self.select_button = QtWidgets.QToolButton(parent=self.widget)
        self.select_button.setObjectName("select_button")
        self.horizontalLayout_3.addWidget(self.select_button)
        self.widget_2 = QtWidgets.QWidget(parent=ImportObjectDialog)
        self.widget_2.setGeometry(QtCore.QRect(10, 40, 371, 38))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.attr_name = QtWidgets.QCheckBox(parent=self.widget_2)
        self.attr_name.setObjectName("attr_name")
        self.horizontalLayout.addWidget(self.attr_name)
        self.symbol_list = QtWidgets.QComboBox(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symbol_list.sizePolicy().hasHeightForWidth())
        self.symbol_list.setSizePolicy(sizePolicy)
        self.symbol_list.setObjectName("symbol_list")
        self.horizontalLayout.addWidget(self.symbol_list)
        self.widget_3 = QtWidgets.QWidget(parent=ImportObjectDialog)
        self.widget_3.setGeometry(QtCore.QRect(10, 70, 371, 38))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.as_symbol_name_label = QtWidgets.QLabel(parent=self.widget_3)
        self.as_symbol_name_label.setObjectName("as_symbol_name_label")
        self.horizontalLayout_2.addWidget(self.as_symbol_name_label)
        self.symbol_name_edit = QtWidgets.QLineEdit(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symbol_name_edit.sizePolicy().hasHeightForWidth())
        self.symbol_name_edit.setSizePolicy(sizePolicy)
        self.symbol_name_edit.setObjectName("symbol_name_edit")
        self.horizontalLayout_2.addWidget(self.symbol_name_edit)

        self.retranslateUi(ImportObjectDialog)
        self.buttonBox.accepted.connect(ImportObjectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImportObjectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImportObjectDialog)

    def retranslateUi(self, ImportObjectDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportObjectDialog.setWindowTitle(_translate("ImportObjectDialog", "Import an Object"))
        self.source_module.setText(_translate("ImportObjectDialog", "Source Module:          "))
        self.select_button.setText(_translate("ImportObjectDialog", "..."))
        self.attr_name.setText(_translate("ImportObjectDialog", "Attribute name:  "))
        self.as_symbol_name_label.setText(_translate("ImportObjectDialog", "As Symbol name:       "))
