# Form implementation generated from reading ui file 'origame\gui\part_editors\ui_files\plot_export_data_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlotExportDataDialog(object):
    def setupUi(self, PlotExportDataDialog):
        PlotExportDataDialog.setObjectName("PlotExportDataDialog")
        PlotExportDataDialog.resize(378, 143)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotExportDataDialog.sizePolicy().hasHeightForWidth())
        PlotExportDataDialog.setSizePolicy(sizePolicy)
        PlotExportDataDialog.setWindowTitle("Export Plot Data")
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotExportDataDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=PlotExportDataDialog)
        self.label_2.setToolTip("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.file_path_line_edit = QtWidgets.QLineEdit(parent=PlotExportDataDialog)
        self.file_path_line_edit.setText("")
        self.file_path_line_edit.setPlaceholderText("Example: C:\\My Documents\\mydata.xls")
        self.file_path_line_edit.setObjectName("file_path_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.file_path_line_edit)
        self.label = QtWidgets.QLabel(parent=PlotExportDataDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.sheet_line_edit = QtWidgets.QLineEdit(parent=PlotExportDataDialog)
        self.sheet_line_edit.setText("Sheet1")
        self.sheet_line_edit.setPlaceholderText("Example: Sheet1")
        self.sheet_line_edit.setObjectName("sheet_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sheet_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(parent=PlotExportDataDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(PlotExportDataDialog)
        self.button_box.accepted.connect(PlotExportDataDialog.accept) # type: ignore
        self.button_box.rejected.connect(PlotExportDataDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PlotExportDataDialog)

    def retranslateUi(self, PlotExportDataDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("PlotExportDataDialog", "Excel File Path:"))
        self.file_path_line_edit.setToolTip(_translate("PlotExportDataDialog", "Enter the path to the file to export to"))
        self.label.setText(_translate("PlotExportDataDialog", "Sheet Name:"))
        self.sheet_line_edit.setToolTip(_translate("PlotExportDataDialog", "Enter the name of the sheet"))
