# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\part_editors\ui_files\pulse_part_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PulsePartEditorWidget(object):
    def setupUi(self, PulsePartEditorWidget):
        PulsePartEditorWidget.setObjectName("PulsePartEditorWidget")
        PulsePartEditorWidget.resize(242, 267)
        self.verticalLayout = QtWidgets.QVBoxLayout(PulsePartEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(PulsePartEditorWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.days_edit = QtWidgets.QSpinBox(self.groupBox_3)
        self.days_edit.setMaximum(999999999)
        self.days_edit.setProperty("value", 1)
        self.days_edit.setObjectName("days_edit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.days_edit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.hours_edit = QtWidgets.QSpinBox(self.groupBox_3)
        self.hours_edit.setMaximum(999999999)
        self.hours_edit.setObjectName("hours_edit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hours_edit)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.minutes_edit = QtWidgets.QSpinBox(self.groupBox_3)
        self.minutes_edit.setMaximum(999999999)
        self.minutes_edit.setObjectName("minutes_edit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minutes_edit)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.seconds_edit = QtWidgets.QSpinBox(self.groupBox_3)
        self.seconds_edit.setMaximum(999999999)
        self.seconds_edit.setObjectName("seconds_edit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.seconds_edit)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(PulsePartEditorWidget)
        self.label_8.setMinimumSize(QtCore.QSize(65, 0))
        self.label_8.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.active_state_radio = QtWidgets.QRadioButton(PulsePartEditorWidget)
        self.active_state_radio.setObjectName("active_state_radio")
        self.horizontalLayout.addWidget(self.active_state_radio)
        self.inactive_state_radio = QtWidgets.QRadioButton(PulsePartEditorWidget)
        self.inactive_state_radio.setObjectName("inactive_state_radio")
        self.horizontalLayout.addWidget(self.inactive_state_radio)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 12, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(PulsePartEditorWidget)
        self.label_9.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.priority_edit = QtWidgets.QDoubleSpinBox(PulsePartEditorWidget)
        self.priority_edit.setDecimals(3)
        self.priority_edit.setMaximum(1000000.0)
        self.priority_edit.setSingleStep(1.0)
        self.priority_edit.setProperty("value", 1000000.0)
        self.priority_edit.setObjectName("priority_edit")
        self.horizontalLayout_2.addWidget(self.priority_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(PulsePartEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(PulsePartEditorWidget)

    def retranslateUi(self, PulsePartEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_3.setTitle(_translate("PulsePartEditorWidget", "Period"))
        self.label_4.setText(_translate("PulsePartEditorWidget", "Days:"))
        self.label_5.setText(_translate("PulsePartEditorWidget", "Hours:"))
        self.label_6.setText(_translate("PulsePartEditorWidget", "Minutes:"))
        self.label_7.setText(_translate("PulsePartEditorWidget", "Seconds:"))
        self.label_8.setText(_translate("PulsePartEditorWidget", "   State:"))
        self.active_state_radio.setText(_translate("PulsePartEditorWidget", "Active"))
        self.inactive_state_radio.setText(_translate("PulsePartEditorWidget", "Inactive"))
        self.label_9.setText(_translate("PulsePartEditorWidget", "   Priority:"))

