# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\part_editors\ui_files\scenario_part_editor_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScenarioPartEditorPanel(object):
    def setupUi(self, ScenarioPartEditorPanel):
        ScenarioPartEditorPanel.setObjectName("ScenarioPartEditorPanel")
        ScenarioPartEditorPanel.resize(344, 148)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ScenarioPartEditorPanel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.part_path = QtWidgets.QLineEdit(ScenarioPartEditorPanel)
        self.part_path.setMinimumSize(QtCore.QSize(0, 0))
        self.part_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.part_path.setReadOnly(True)
        self.part_path.setObjectName("part_path")
        self.verticalLayout.addWidget(self.part_path)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(ScenarioPartEditorPanel)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.part_name = QtWidgets.QLineEdit(ScenarioPartEditorPanel)
        self.part_name.setObjectName("part_name")
        self.horizontalLayout_2.addWidget(self.part_name)
        self.go_to_part = QtWidgets.QToolButton(ScenarioPartEditorPanel)
        self.go_to_part.setObjectName("go_to_part")
        self.horizontalLayout_2.addWidget(self.go_to_part)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.content_placeholder = QtWidgets.QVBoxLayout()
        self.content_placeholder.setObjectName("content_placeholder")
        self.verticalLayout_2.addLayout(self.content_placeholder)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.part_help_button = QtWidgets.QPushButton(ScenarioPartEditorPanel)
        self.part_help_button.setObjectName("part_help_button")
        self.horizontalLayout.addWidget(self.part_help_button)
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(ScenarioPartEditorPanel)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout.addWidget(self.button_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ScenarioPartEditorPanel)
        QtCore.QMetaObject.connectSlotsByName(ScenarioPartEditorPanel)

    def retranslateUi(self, ScenarioPartEditorPanel):
        _translate = QtCore.QCoreApplication.translate
        ScenarioPartEditorPanel.setWindowTitle(_translate("ScenarioPartEditorPanel", "Form"))
        self.label_4.setText(_translate("ScenarioPartEditorPanel", "Name"))
        self.go_to_part.setText(_translate("ScenarioPartEditorPanel", "Go to Part"))
        self.part_help_button.setText(_translate("ScenarioPartEditorPanel", "Help"))

