# Form implementation generated from reading ui file 'origame\gui\part_editors\ui_files\table_filter_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TableFilterDialog(object):
    def setupUi(self, TableFilterDialog):
        TableFilterDialog.setObjectName("TableFilterDialog")
        TableFilterDialog.resize(400, 102)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TableFilterDialog.sizePolicy().hasHeightForWidth())
        TableFilterDialog.setSizePolicy(sizePolicy)
        TableFilterDialog.setMinimumSize(QtCore.QSize(0, 102))
        TableFilterDialog.setMaximumSize(QtCore.QSize(16777215, 102))
        self.verticalLayout = QtWidgets.QVBoxLayout(TableFilterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=TableFilterDialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.sql_filter_line_edit = QtWidgets.QLineEdit(parent=TableFilterDialog)
        self.sql_filter_line_edit.setText("")
        self.sql_filter_line_edit.setObjectName("sql_filter_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sql_filter_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.button_box = QtWidgets.QDialogButtonBox(parent=TableFilterDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(TableFilterDialog)
        self.button_box.accepted.connect(TableFilterDialog.accept) # type: ignore
        self.button_box.rejected.connect(TableFilterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TableFilterDialog)

    def retranslateUi(self, TableFilterDialog):
        _translate = QtCore.QCoreApplication.translate
        TableFilterDialog.setWindowTitle(_translate("TableFilterDialog", "Filter"))
        self.label.setText(_translate("TableFilterDialog", "Click OK to apply the SQLite WHERE statement and filter the table data (data will not be filtered in the editor)."))
        self.sql_filter_line_edit.setPlaceholderText(_translate("TableFilterDialog", "SQL \'WHERE\' Example: [Col1] = \'value\'"))
