# Form implementation generated from reading ui file 'origame\gui\part_editors\ui_files\table_index_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TableIndexDialog(object):
    def setupUi(self, TableIndexDialog):
        TableIndexDialog.setObjectName("TableIndexDialog")
        TableIndexDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TableIndexDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_button = QtWidgets.QToolButton(parent=TableIndexDialog)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_3.addWidget(self.add_button)
        self.delete_button = QtWidgets.QToolButton(parent=TableIndexDialog)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_3.addWidget(self.delete_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_widget = QtWidgets.QTableWidget(parent=TableIndexDialog)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(1)
        self.table_widget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setItem(1, 0, item)
        self.table_widget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table_widget)
        self.button_box = QtWidgets.QDialogButtonBox(parent=TableIndexDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(TableIndexDialog)
        self.button_box.accepted.connect(TableIndexDialog.accept) # type: ignore
        self.button_box.rejected.connect(TableIndexDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TableIndexDialog)
        TableIndexDialog.setTabOrder(self.add_button, self.delete_button)
        TableIndexDialog.setTabOrder(self.delete_button, self.table_widget)

    def retranslateUi(self, TableIndexDialog):
        _translate = QtCore.QCoreApplication.translate
        TableIndexDialog.setWindowTitle(_translate("TableIndexDialog", "Table Index"))
        self.add_button.setText(_translate("TableIndexDialog", "Add"))
        self.delete_button.setText(_translate("TableIndexDialog", "Delete"))
        item = self.table_widget.verticalHeaderItem(0)
        item.setText(_translate("TableIndexDialog", "1"))
        item = self.table_widget.verticalHeaderItem(1)
        item.setText(_translate("TableIndexDialog", "2"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("TableIndexDialog", "Enter Column Names to Index"))
        __sortingEnabled = self.table_widget.isSortingEnabled()
        self.table_widget.setSortingEnabled(False)
        item = self.table_widget.item(0, 0)
        item.setText(_translate("TableIndexDialog", "Column1"))
        item = self.table_widget.item(1, 0)
        item.setText(_translate("TableIndexDialog", "Column3, Column2"))
        self.table_widget.setSortingEnabled(__sortingEnabled)
