# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\part_editors\ui_files\time_part_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimePartEditorWidget(object):
    def setupUi(self, TimePartEditorWidget):
        TimePartEditorWidget.setObjectName("TimePartEditorWidget")
        TimePartEditorWidget.resize(171, 210)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimePartEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(TimePartEditorWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.days_edit = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.days_edit.setMaximum(9999999.0)
        self.days_edit.setObjectName("days_edit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.days_edit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.hours_edit = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.hours_edit.setObjectName("hours_edit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hours_edit)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.minutes_edit = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.minutes_edit.setObjectName("minutes_edit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minutes_edit)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.seconds_edit = QtWidgets.QSpinBox(self.groupBox_3)
        self.seconds_edit.setObjectName("seconds_edit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.seconds_edit)
        self.reset = QtWidgets.QPushButton(self.groupBox_3)
        self.reset.setObjectName("reset")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.reset)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(TimePartEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(TimePartEditorWidget)

    def retranslateUi(self, TimePartEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_3.setTitle(_translate("TimePartEditorWidget", "Elapsed Time"))
        self.label_4.setText(_translate("TimePartEditorWidget", "Days:"))
        self.label_5.setText(_translate("TimePartEditorWidget", "Hours:"))
        self.label_6.setText(_translate("TimePartEditorWidget", "Minutes:"))
        self.label_7.setText(_translate("TimePartEditorWidget", "Seconds:"))
        self.reset.setText(_translate("TimePartEditorWidget", "Reset"))

