# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\sim\ui_files\event_queue.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimulationEventQueue(object):
    def setupUi(self, SimulationEventQueue):
        SimulationEventQueue.setObjectName("SimulationEventQueue")
        SimulationEventQueue.resize(723, 224)
        self.verticalLayout = QtWidgets.QVBoxLayout(SimulationEventQueue)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_tool_button = QtWidgets.QToolButton(SimulationEventQueue)
        self.edit_tool_button.setMinimumSize(QtCore.QSize(100, 25))
        self.edit_tool_button.setObjectName("edit_tool_button")
        self.horizontalLayout.addWidget(self.edit_tool_button)
        self.delete_tool_button = QtWidgets.QToolButton(SimulationEventQueue)
        self.delete_tool_button.setMinimumSize(QtCore.QSize(100, 25))
        self.delete_tool_button.setObjectName("delete_tool_button")
        self.horizontalLayout.addWidget(self.delete_tool_button)
        self.clear_queue_tool_button = QtWidgets.QToolButton(SimulationEventQueue)
        self.clear_queue_tool_button.setMinimumSize(QtCore.QSize(100, 25))
        self.clear_queue_tool_button.setObjectName("clear_queue_tool_button")
        self.horizontalLayout.addWidget(self.clear_queue_tool_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clear_filter_button = QtWidgets.QPushButton(SimulationEventQueue)
        self.clear_filter_button.setObjectName("clear_filter_button")
        self.horizontalLayout.addWidget(self.clear_filter_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.event_queue_table_widget = QtWidgets.QTableWidget(SimulationEventQueue)
        self.event_queue_table_widget.setAutoScroll(False)
        self.event_queue_table_widget.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.event_queue_table_widget.setDragDropOverwriteMode(False)
        self.event_queue_table_widget.setAlternatingRowColors(True)
        self.event_queue_table_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.event_queue_table_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.event_queue_table_widget.setRowCount(0)
        self.event_queue_table_widget.setColumnCount(7)
        self.event_queue_table_widget.setObjectName("event_queue_table_widget")
        item = QtWidgets.QTableWidgetItem()
        self.event_queue_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_queue_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_queue_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_queue_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_queue_table_widget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_queue_table_widget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_queue_table_widget.setHorizontalHeaderItem(6, item)
        self.event_queue_table_widget.horizontalHeader().setDefaultSectionSize(100)
        self.event_queue_table_widget.horizontalHeader().setMinimumSectionSize(34)
        self.verticalLayout.addWidget(self.event_queue_table_widget)

        self.retranslateUi(SimulationEventQueue)
        QtCore.QMetaObject.connectSlotsByName(SimulationEventQueue)
        SimulationEventQueue.setTabOrder(self.edit_tool_button, self.delete_tool_button)
        SimulationEventQueue.setTabOrder(self.delete_tool_button, self.clear_queue_tool_button)
        SimulationEventQueue.setTabOrder(self.clear_queue_tool_button, self.event_queue_table_widget)

    def retranslateUi(self, SimulationEventQueue):
        _translate = QtCore.QCoreApplication.translate
        SimulationEventQueue.setWindowTitle(_translate("SimulationEventQueue", "Simulation Event Queue"))
        self.edit_tool_button.setToolTip(_translate("SimulationEventQueue", "Edit an event in the queue"))
        self.edit_tool_button.setText(_translate("SimulationEventQueue", "Edit"))
        self.delete_tool_button.setToolTip(_translate("SimulationEventQueue", "Remove an event from the queue"))
        self.delete_tool_button.setText(_translate("SimulationEventQueue", "Delete"))
        self.clear_queue_tool_button.setToolTip(_translate("SimulationEventQueue", "Remove all events from the queue"))
        self.clear_queue_tool_button.setText(_translate("SimulationEventQueue", "Clear Queue"))
        self.clear_filter_button.setToolTip(_translate("SimulationEventQueue", "View all the events"))
        self.clear_filter_button.setText(_translate("SimulationEventQueue", "Clear Filter"))
        item = self.event_queue_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("SimulationEventQueue", "Event ID"))
        item = self.event_queue_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("SimulationEventQueue", "Time"))
        item = self.event_queue_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("SimulationEventQueue", "Priority"))
        item = self.event_queue_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("SimulationEventQueue", "Part"))
        item = self.event_queue_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("SimulationEventQueue", "Part Type"))
        item = self.event_queue_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("SimulationEventQueue", "Args"))
        item = self.event_queue_table_widget.horizontalHeaderItem(6)
        item.setText(_translate("SimulationEventQueue", "Path"))

