# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'event_queue_item.ui'
#
# Created: Mon May  9 11:45:49 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimulationEventQueueItemDialog(object):
    def setupUi(self, SimulationEventQueueItemDialog):
        SimulationEventQueueItemDialog.setObjectName("SimulationEventQueueItemDialog")
        SimulationEventQueueItemDialog.resize(462, 220)
        self.formLayout = QtWidgets.QFormLayout(SimulationEventQueueItemDialog)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.path_line_edit = QtWidgets.QLineEdit(SimulationEventQueueItemDialog)
        self.path_line_edit.setReadOnly(True)
        self.path_line_edit.setObjectName("path_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.path_line_edit)
        self.label_5 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.name_line_edit = QtWidgets.QLineEdit(SimulationEventQueueItemDialog)
        self.name_line_edit.setReadOnly(True)
        self.name_line_edit.setObjectName("name_line_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.name_line_edit)
        self.label_4 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.param_line_edit = QtWidgets.QLineEdit(SimulationEventQueueItemDialog)
        self.param_line_edit.setText("")
        self.param_line_edit.setObjectName("param_line_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.param_line_edit)
        self.label = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.priority_double_spin_box = QtWidgets.QDoubleSpinBox(SimulationEventQueueItemDialog)
        self.priority_double_spin_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.priority_double_spin_box.setDecimals(3)
        self.priority_double_spin_box.setMaximum(1000000.0)
        self.priority_double_spin_box.setSingleStep(1.0)
        self.priority_double_spin_box.setProperty("value", 0.0)
        self.priority_double_spin_box.setObjectName("priority_double_spin_box")
        self.horizontalLayout.addWidget(self.priority_double_spin_box)
        self.asap_check_box = QtWidgets.QCheckBox(SimulationEventQueueItemDialog)
        self.asap_check_box.setText("ASAP")
        self.asap_check_box.setChecked(False)
        self.asap_check_box.setObjectName("asap_check_box")
        self.horizontalLayout.addWidget(self.asap_check_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.ok_cancel_button_box = QtWidgets.QDialogButtonBox(SimulationEventQueueItemDialog)
        self.ok_cancel_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.ok_cancel_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok_cancel_button_box.setObjectName("ok_cancel_button_box")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.ok_cancel_button_box)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.days_spinbox = QtWidgets.QSpinBox(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.days_spinbox.sizePolicy().hasHeightForWidth())
        self.days_spinbox.setSizePolicy(sizePolicy)
        self.days_spinbox.setMinimumSize(QtCore.QSize(70, 0))
        self.days_spinbox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.days_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.days_spinbox.setMaximum(9999)
        self.days_spinbox.setProperty("value", 0)
        self.days_spinbox.setDisplayIntegerBase(10)
        self.days_spinbox.setObjectName("days_spinbox")
        self.horizontalLayout_2.addWidget(self.days_spinbox)
        self.label_6 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_10 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.hours_spinbox = QtWidgets.QSpinBox(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hours_spinbox.sizePolicy().hasHeightForWidth())
        self.hours_spinbox.setSizePolicy(sizePolicy)
        self.hours_spinbox.setMinimumSize(QtCore.QSize(30, 0))
        self.hours_spinbox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.hours_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.hours_spinbox.setMaximum(23)
        self.hours_spinbox.setProperty("value", 0)
        self.hours_spinbox.setObjectName("hours_spinbox")
        self.horizontalLayout_2.addWidget(self.hours_spinbox)
        self.label_7 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.minutes_spinbox = QtWidgets.QSpinBox(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minutes_spinbox.sizePolicy().hasHeightForWidth())
        self.minutes_spinbox.setSizePolicy(sizePolicy)
        self.minutes_spinbox.setMinimumSize(QtCore.QSize(30, 0))
        self.minutes_spinbox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.minutes_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.minutes_spinbox.setMaximum(59)
        self.minutes_spinbox.setProperty("value", 0)
        self.minutes_spinbox.setObjectName("minutes_spinbox")
        self.horizontalLayout_2.addWidget(self.minutes_spinbox)
        self.label_8 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.seconds_spinbox = QtWidgets.QSpinBox(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seconds_spinbox.sizePolicy().hasHeightForWidth())
        self.seconds_spinbox.setSizePolicy(sizePolicy)
        self.seconds_spinbox.setMinimumSize(QtCore.QSize(30, 0))
        self.seconds_spinbox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.seconds_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.seconds_spinbox.setMaximum(59)
        self.seconds_spinbox.setProperty("value", 0)
        self.seconds_spinbox.setObjectName("seconds_spinbox")
        self.horizontalLayout_2.addWidget(self.seconds_spinbox)
        self.label_9 = QtWidgets.QLabel(SimulationEventQueueItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)

        self.retranslateUi(SimulationEventQueueItemDialog)
        self.ok_cancel_button_box.accepted.connect(SimulationEventQueueItemDialog.accept)
        self.ok_cancel_button_box.rejected.connect(SimulationEventQueueItemDialog.reject)
        self.asap_check_box.toggled['bool'].connect(self.priority_double_spin_box.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(SimulationEventQueueItemDialog)
        SimulationEventQueueItemDialog.setTabOrder(self.path_line_edit, self.name_line_edit)
        SimulationEventQueueItemDialog.setTabOrder(self.name_line_edit, self.param_line_edit)
        SimulationEventQueueItemDialog.setTabOrder(self.param_line_edit, self.days_spinbox)
        SimulationEventQueueItemDialog.setTabOrder(self.days_spinbox, self.hours_spinbox)
        SimulationEventQueueItemDialog.setTabOrder(self.hours_spinbox, self.minutes_spinbox)
        SimulationEventQueueItemDialog.setTabOrder(self.minutes_spinbox, self.seconds_spinbox)
        SimulationEventQueueItemDialog.setTabOrder(self.seconds_spinbox, self.priority_double_spin_box)
        SimulationEventQueueItemDialog.setTabOrder(self.priority_double_spin_box, self.asap_check_box)

    def retranslateUi(self, SimulationEventQueueItemDialog):
        _translate = QtCore.QCoreApplication.translate
        SimulationEventQueueItemDialog.setWindowTitle(_translate("SimulationEventQueueItemDialog", "Simulation Event Queue: Create/Edit Item"))
        self.label_3.setText(_translate("SimulationEventQueueItemDialog", "Path:"))
        self.path_line_edit.setText(_translate("SimulationEventQueueItemDialog", "actor1/actor4"))
        self.label_5.setText(_translate("SimulationEventQueueItemDialog", "Function Name:"))
        self.name_line_edit.setText(_translate("SimulationEventQueueItemDialog", "assign"))
        self.label_4.setText(_translate("SimulationEventQueueItemDialog", "Arguments:"))
        self.label.setText(_translate("SimulationEventQueueItemDialog", "Time:"))
        self.label_2.setText(_translate("SimulationEventQueueItemDialog", "Priority:"))
        self.label_6.setText(_translate("SimulationEventQueueItemDialog", "dddd"))
        self.label_7.setText(_translate("SimulationEventQueueItemDialog", "hh"))
        self.label_8.setText(_translate("SimulationEventQueueItemDialog", "mm"))
        self.label_9.setText(_translate("SimulationEventQueueItemDialog", "ss"))

