# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\actor_part.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActorPartWidget(object):
    def setupUi(self, ActorPartWidget):
        ActorPartWidget.setObjectName("ActorPartWidget")
        ActorPartWidget.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ActorPartWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.retranslateUi(ActorPartWidget)
        QtCore.QMetaObject.connectSlotsByName(ActorPartWidget)

    def retranslateUi(self, ActorPartWidget):
        _translate = QtCore.QCoreApplication.translate
        ActorPartWidget.setWindowTitle(_translate("ActorPartWidget", "Form"))

