# Form implementation generated from reading ui file 'origame\gui\actor_2d_view\ui_files\button_part.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ButtonPartWidget(object):
    def setupUi(self, ButtonPartWidget):
        ButtonPartWidget.setObjectName("ButtonPartWidget")
        ButtonPartWidget.resize(200, 200)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ButtonPartWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_button = SvgPushButton(parent=ButtonPartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button.sizePolicy().hasHeightForWidth())
        self.push_button.setSizePolicy(sizePolicy)
        self.push_button.setText("")
        self.push_button.setCheckable(True)
        self.push_button.setObjectName("push_button")
        self.horizontalLayout.addWidget(self.push_button)

        self.retranslateUi(ButtonPartWidget)
        QtCore.QMetaObject.connectSlotsByName(ButtonPartWidget)

    def retranslateUi(self, ButtonPartWidget):
        _translate = QtCore.QCoreApplication.translate
        ButtonPartWidget.setWindowTitle(_translate("ButtonPartWidget", "Form"))
from .custom_widgets import SvgPushButton
