# Form implementation generated from reading ui file 'origame\gui\actor_2d_view\ui_files\comment_box.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommentBox(object):
    def setupUi(self, CommentBox):
        CommentBox.setObjectName("CommentBox")
        CommentBox.resize(233, 91)
        self.verticalLayout = QtWidgets.QVBoxLayout(CommentBox)
        self.verticalLayout.setContentsMargins(2, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QWidget(parent=CommentBox)
        self.label.setObjectName("label")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.label)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cue = QtWidgets.QLabel(parent=self.label)
        self.cue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cue.setObjectName("cue")
        self.verticalLayout_2.addWidget(self.cue)
        spacerItem = QtWidgets.QSpacerItem(20, 145, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.label)
        self.comment_text = QtWidgets.QTextEdit(parent=CommentBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_text.sizePolicy().hasHeightForWidth())
        self.comment_text.setSizePolicy(sizePolicy)
        self.comment_text.setReadOnly(True)
        self.comment_text.setObjectName("comment_text")
        self.horizontalLayout.addWidget(self.comment_text)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CommentBox)
        QtCore.QMetaObject.connectSlotsByName(CommentBox)

    def retranslateUi(self, CommentBox):
        _translate = QtCore.QCoreApplication.translate
        self.cue.setText(_translate("CommentBox", "i"))
