# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\clock_part.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClockPartWidget(object):
    def setupUi(self, ClockPartWidget):
        ClockPartWidget.setObjectName("ClockPartWidget")
        ClockPartWidget.resize(602, 90)
        ClockPartWidget.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";background-color: rgb(255, 255, 255);")
        self.formLayout = QtWidgets.QFormLayout(ClockPartWidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ClockPartWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dateTimeEdit = QtWidgets.QLineEdit(ClockPartWidget)
        self.dateTimeEdit.setEnabled(False)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.label_2 = QtWidgets.QLabel(ClockPartWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ticksEdit = QtWidgets.QLineEdit(ClockPartWidget)
        self.ticksEdit.setEnabled(False)
        self.ticksEdit.setReadOnly(True)
        self.ticksEdit.setObjectName("ticksEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ticksEdit)
        self.label_4 = QtWidgets.QLabel(ClockPartWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tickPeriodEdit = QtWidgets.QLineEdit(ClockPartWidget)
        self.tickPeriodEdit.setEnabled(False)
        self.tickPeriodEdit.setReadOnly(True)
        self.tickPeriodEdit.setObjectName("tickPeriodEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tickPeriodEdit)

        self.retranslateUi(ClockPartWidget)
        QtCore.QMetaObject.connectSlotsByName(ClockPartWidget)

    def retranslateUi(self, ClockPartWidget):
        _translate = QtCore.QCoreApplication.translate
        ClockPartWidget.setWindowTitle(_translate("ClockPartWidget", "Clock Part"))
        self.label.setText(_translate("ClockPartWidget", "Date/Time:"))
        self.label_2.setText(_translate("ClockPartWidget", "Ticks:"))
        self.ticksEdit.setText(_translate("ClockPartWidget", "0"))
        self.label_4.setText(_translate("ClockPartWidget", "Tick Period:"))
        self.tickPeriodEdit.setText(_translate("ClockPartWidget", "1 Day"))

