# Form implementation generated from reading ui file 'origame\gui\actor_2d_view\ui_files\frameless_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FramelessPartWidget(object):
    def setupUi(self, FramelessPartWidget):
        FramelessPartWidget.setObjectName("FramelessPartWidget")
        FramelessPartWidget.resize(265, 173)
        self.verticalLayout = QtWidgets.QVBoxLayout(FramelessPartWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(FramelessPartWidget)
        QtCore.QMetaObject.connectSlotsByName(FramelessPartWidget)

    def retranslateUi(self, FramelessPartWidget):
        pass
