# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\label_button_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabelButtonItem(object):
    def setupUi(self, LabelButtonItem):
        LabelButtonItem.setObjectName("LabelButtonItem")
        LabelButtonItem.resize(398, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(LabelButtonItem)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(LabelButtonItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(LabelButtonItem)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(LabelButtonItem)
        QtCore.QMetaObject.connectSlotsByName(LabelButtonItem)

    def retranslateUi(self, LabelButtonItem):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("LabelButtonItem", "TextLabel"))
        self.pushButton.setText(_translate("LabelButtonItem", "Run"))

