# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\list_and_fire.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListAndFireDialog(object):
    def setupUi(self, ListAndFireDialog):
        ListAndFireDialog.setObjectName("ListAndFireDialog")
        ListAndFireDialog.resize(555, 548)
        self.verticalLayout = QtWidgets.QVBoxLayout(ListAndFireDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.prompt = QtWidgets.QLabel(ListAndFireDialog)
        self.prompt.setObjectName("prompt")
        self.verticalLayout.addWidget(self.prompt)
        self.listWidget = QtWidgets.QListWidget(ListAndFireDialog)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(ListAndFireDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ListAndFireDialog)
        self.buttonBox.accepted.connect(ListAndFireDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ListAndFireDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ListAndFireDialog)

    def retranslateUi(self, ListAndFireDialog):
        _translate = QtCore.QCoreApplication.translate
        ListAndFireDialog.setWindowTitle(_translate("ListAndFireDialog", "Function List"))
        self.prompt.setText(_translate("ListAndFireDialog", "Please select a function to run:"))

