# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\pulse_part.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PulsePartWidget(object):
    def setupUi(self, PulsePartWidget):
        PulsePartWidget.setObjectName("PulsePartWidget")
        PulsePartWidget.resize(292, 102)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PulsePartWidget.sizePolicy().hasHeightForWidth())
        PulsePartWidget.setSizePolicy(sizePolicy)
        PulsePartWidget.setMinimumSize(QtCore.QSize(0, 102))
        PulsePartWidget.setMaximumSize(QtCore.QSize(16777215, 102))
        PulsePartWidget.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";background-color: rgb(255, 255, 255);")
        self.formLayout = QtWidgets.QFormLayout(PulsePartWidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(PulsePartWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.period_edit = QtWidgets.QLineEdit(PulsePartWidget)
        self.period_edit.setEnabled(False)
        self.period_edit.setReadOnly(True)
        self.period_edit.setObjectName("period_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.period_edit)
        self.label_2 = QtWidgets.QLabel(PulsePartWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.state_edit = QtWidgets.QLineEdit(PulsePartWidget)
        self.state_edit.setEnabled(False)
        self.state_edit.setText("")
        self.state_edit.setReadOnly(True)
        self.state_edit.setObjectName("state_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.state_edit)
        self.label_4 = QtWidgets.QLabel(PulsePartWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.priority_edit = QtWidgets.QLineEdit(PulsePartWidget)
        self.priority_edit.setEnabled(False)
        self.priority_edit.setText("")
        self.priority_edit.setReadOnly(True)
        self.priority_edit.setObjectName("priority_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.priority_edit)

        self.retranslateUi(PulsePartWidget)
        QtCore.QMetaObject.connectSlotsByName(PulsePartWidget)

    def retranslateUi(self, PulsePartWidget):
        _translate = QtCore.QCoreApplication.translate
        PulsePartWidget.setWindowTitle(_translate("PulsePartWidget", "Pulse Part"))
        self.label.setText(_translate("PulsePartWidget", "Period:"))
        self.label_2.setText(_translate("PulsePartWidget", "State:"))
        self.label_4.setText(_translate("PulsePartWidget", "Priority:"))

