# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\parent_actor_proxy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParentActorProxyWidget(object):
    def setupUi(self, ParentActorProxyWidget):
        ParentActorProxyWidget.setObjectName("ParentActorProxyWidget")
        ParentActorProxyWidget.resize(110, 32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParentActorProxyWidget.sizePolicy().hasHeightForWidth())
        ParentActorProxyWidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ParentActorProxyWidget)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.small_icon = QSvgWidget(ParentActorProxyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.small_icon.sizePolicy().hasHeightForWidth())
        self.small_icon.setSizePolicy(sizePolicy)
        self.small_icon.setObjectName("small_icon")
        self.horizontalLayout.addWidget(self.small_icon)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.name_label = QtWidgets.QLabel(ParentActorProxyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        self.name_label.setStyleSheet("font-size: 18px; color: white")
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(ParentActorProxyWidget)
        QtCore.QMetaObject.connectSlotsByName(ParentActorProxyWidget)

    def retranslateUi(self, ParentActorProxyWidget):
        _translate = QtCore.QCoreApplication.translate
        self.name_label.setText(_translate("ParentActorProxyWidget", "<html><head/><body><p><span style=\" font-size:11pt;\">TextLabel</span></p></body></html>"))
from PyQt5.QtSvg import QSvgWidget
