# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\sql_part.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SqlPartWidget(object):
    def setupUi(self, SqlPartWidget):
        SqlPartWidget.setObjectName("SqlPartWidget")
        SqlPartWidget.resize(602, 223)
        self.verticalLayout = QtWidgets.QVBoxLayout(SqlPartWidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_parameters = QtWidgets.QLabel(SqlPartWidget)
        self.label_parameters.setObjectName("label_parameters")
        self.horizontalLayout.addWidget(self.label_parameters)
        self.parameters = CallParameters(SqlPartWidget)
        self.parameters.setReadOnly(True)
        self.parameters.setObjectName("parameters")
        self.horizontalLayout.addWidget(self.parameters)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.script = ScriptEditBox(SqlPartWidget)
        self.script.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.script.setReadOnly(True)
        self.script.setObjectName("script")
        self.verticalLayout.addWidget(self.script)

        self.retranslateUi(SqlPartWidget)
        QtCore.QMetaObject.connectSlotsByName(SqlPartWidget)

    def retranslateUi(self, SqlPartWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label_parameters.setText(_translate("SqlPartWidget", "Parameters:"))
from .custom_widgets import CallParameters, ScriptEditBox
