# Form implementation generated from reading ui file 'origame\gui\actor_2d_view\ui_files\time_part.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimePartWidget(object):
    def setupUi(self, TimePartWidget):
        TimePartWidget.setObjectName("TimePartWidget")
        TimePartWidget.resize(198, 38)
        TimePartWidget.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";background-color: rgb(255, 255, 255);")
        self.formLayout = QtWidgets.QFormLayout(TimePartWidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=TimePartWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.elapsed_time = QtWidgets.QLineEdit(parent=TimePartWidget)
        self.elapsed_time.setEnabled(False)
        self.elapsed_time.setReadOnly(True)
        self.elapsed_time.setObjectName("elapsed_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.elapsed_time)

        self.retranslateUi(TimePartWidget)
        QtCore.QMetaObject.connectSlotsByName(TimePartWidget)

    def retranslateUi(self, TimePartWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("TimePartWidget", "Elapsed Time:"))
