# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\actor_2d_view\ui_files\view_panel_toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Actor2dPanelToolbar(object):
    def setupUi(self, Actor2dPanelToolbar):
        Actor2dPanelToolbar.setObjectName("Actor2dPanelToolbar")
        Actor2dPanelToolbar.resize(92, 329)
        self.verticalLayout = QtWidgets.QVBoxLayout(Actor2dPanelToolbar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_cut = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_cut.setObjectName("button_cut")
        self.verticalLayout.addWidget(self.button_cut)
        self.button_copy = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_copy.setObjectName("button_copy")
        self.verticalLayout.addWidget(self.button_copy)
        self.button_paste = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_paste.setObjectName("button_paste")
        self.verticalLayout.addWidget(self.button_paste)
        self.button_delete = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_delete.setObjectName("button_delete")
        self.verticalLayout.addWidget(self.button_delete)
        self.button_undo = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_undo.setObjectName("button_undo")
        self.verticalLayout.addWidget(self.button_undo)
        self.button_redo = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_redo.setObjectName("button_redo")
        self.verticalLayout.addWidget(self.button_redo)
        self.line = QtWidgets.QFrame(Actor2dPanelToolbar)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.button_zoom_to_fit_all = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_zoom_to_fit_all.setObjectName("button_zoom_to_fit_all")
        self.verticalLayout.addWidget(self.button_zoom_to_fit_all)
        self.button_zoom_to_selection = QtWidgets.QToolButton(Actor2dPanelToolbar)
        self.button_zoom_to_selection.setObjectName("button_zoom_to_selection")
        self.verticalLayout.addWidget(self.button_zoom_to_selection)
        self.line_2 = QtWidgets.QFrame(Actor2dPanelToolbar)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Actor2dPanelToolbar)
        QtCore.QMetaObject.connectSlotsByName(Actor2dPanelToolbar)

    def retranslateUi(self, Actor2dPanelToolbar):
        _translate = QtCore.QCoreApplication.translate
        self.button_cut.setText(_translate("Actor2dPanelToolbar", "..."))
        self.button_copy.setText(_translate("Actor2dPanelToolbar", "..."))
        self.button_paste.setText(_translate("Actor2dPanelToolbar", "..."))
        self.button_delete.setText(_translate("Actor2dPanelToolbar", "..."))
        self.button_undo.setText(_translate("Actor2dPanelToolbar", "..."))
        self.button_redo.setText(_translate("Actor2dPanelToolbar", "..."))
        self.button_zoom_to_fit_all.setText(_translate("Actor2dPanelToolbar", "..."))
        self.button_zoom_to_selection.setText(_translate("Actor2dPanelToolbar", "..."))

