# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\debugging\ui_files\debugger_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugCodeViewerPanel(object):
    def setupUi(self, DebugCodeViewerPanel):
        DebugCodeViewerPanel.setObjectName("DebugCodeViewerPanel")
        DebugCodeViewerPanel.resize(789, 574)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DebugCodeViewerPanel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(DebugCodeViewerPanel)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(DebugCodeViewerPanel)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.part_name = QtWidgets.QLineEdit(DebugCodeViewerPanel)
        self.part_name.setEnabled(False)
        self.part_name.setObjectName("part_name")
        self.gridLayout.addWidget(self.part_name, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(DebugCodeViewerPanel)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_parameters = QtWidgets.QLabel(DebugCodeViewerPanel)
        self.label_parameters.setObjectName("label_parameters")
        self.gridLayout.addWidget(self.label_parameters, 2, 2, 1, 1)
        self.text_parameters = QtWidgets.QLineEdit(DebugCodeViewerPanel)
        self.text_parameters.setEnabled(False)
        self.text_parameters.setObjectName("text_parameters")
        self.gridLayout.addWidget(self.text_parameters, 2, 3, 1, 1)
        self.part_type = QtWidgets.QLineEdit(DebugCodeViewerPanel)
        self.part_type.setEnabled(False)
        self.part_type.setObjectName("part_type")
        self.gridLayout.addWidget(self.part_type, 0, 1, 1, 3)
        self.part_path = QtWidgets.QLineEdit(DebugCodeViewerPanel)
        self.part_path.setEnabled(False)
        self.part_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.part_path.setObjectName("part_path")
        self.gridLayout.addWidget(self.part_path, 3, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.groupBox = QtWidgets.QGroupBox(DebugCodeViewerPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.code_viewer = ScriptPanel(self.groupBox)
        self.code_viewer.setMinimumSize(QtCore.QSize(400, 0))
        self.code_viewer.setObjectName("code_viewer")
        self.verticalLayout_3.addWidget(self.code_viewer)
        self.main_layout.addWidget(self.groupBox)
        self.ops_panel = DebugOpsPanel(DebugCodeViewerPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ops_panel.sizePolicy().hasHeightForWidth())
        self.ops_panel.setSizePolicy(sizePolicy)
        self.ops_panel.setMinimumSize(QtCore.QSize(300, 0))
        self.ops_panel.setAutoFillBackground(True)
        self.ops_panel.setObjectName("ops_panel")
        self.main_layout.addWidget(self.ops_panel)
        self.verticalLayout.addLayout(self.main_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_close = QtWidgets.QDialogButtonBox(DebugCodeViewerPanel)
        self.button_close.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout.addWidget(self.button_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DebugCodeViewerPanel)
        QtCore.QMetaObject.connectSlotsByName(DebugCodeViewerPanel)

    def retranslateUi(self, DebugCodeViewerPanel):
        _translate = QtCore.QCoreApplication.translate
        DebugCodeViewerPanel.setWindowTitle(_translate("DebugCodeViewerPanel", "Python Debugger"))
        self.label_2.setText(_translate("DebugCodeViewerPanel", "Part Type"))
        self.label_4.setText(_translate("DebugCodeViewerPanel", "Part Name"))
        self.label_3.setText(_translate("DebugCodeViewerPanel", "Part Path"))
        self.label_parameters.setText(_translate("DebugCodeViewerPanel", "Parameters"))
        self.groupBox.setTitle(_translate("DebugCodeViewerPanel", "Python Code"))
from ..debugging.ops_panel import DebugOpsPanel
from ..script_panel import ScriptPanel
