# Form implementation generated from reading ui file 'origame\gui\ui_files\rename_link_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LinkRenameDialog(object):
    def setupUi(self, LinkRenameDialog):
        LinkRenameDialog.setObjectName("LinkRenameDialog")
        LinkRenameDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        LinkRenameDialog.resize(638, 589)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LinkRenameDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_area = QtWidgets.QWidget(parent=LinkRenameDialog)
        self.main_area.setObjectName("main_area")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_area)
        self.verticalLayout.setObjectName("verticalLayout")
        self.current_name_row = QtWidgets.QWidget(parent=self.main_area)
        self.current_name_row.setObjectName("current_name_row")
        self.formLayout = QtWidgets.QFormLayout(self.current_name_row)
        self.formLayout.setContentsMargins(0, -1, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.current_name_label = QtWidgets.QLabel(parent=self.current_name_row)
        self.current_name_label.setObjectName("current_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.current_name_label)
        self.current_name_edit = QtWidgets.QLineEdit(parent=self.current_name_row)
        self.current_name_edit.setReadOnly(True)
        self.current_name_edit.setObjectName("current_name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.current_name_edit)
        self.verticalLayout.addWidget(self.current_name_row)
        self.references_label = QtWidgets.QLabel(parent=self.main_area)
        self.references_label.setObjectName("references_label")
        self.verticalLayout.addWidget(self.references_label)
        self.references = QtWidgets.QTreeWidget(parent=self.main_area)
        self.references.setColumnCount(2)
        self.references.setObjectName("references")
        self.references.headerItem().setText(0, "1")
        self.references.headerItem().setText(1, "2")
        self.references.header().setVisible(True)
        self.references.header().setDefaultSectionSize(200)
        self.verticalLayout.addWidget(self.references)
        self.new_name_row = QtWidgets.QWidget(parent=self.main_area)
        self.new_name_row.setObjectName("new_name_row")
        self.formLayout_2 = QtWidgets.QFormLayout(self.new_name_row)
        self.formLayout_2.setContentsMargins(0, -1, 0, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.new_name_label = QtWidgets.QLabel(parent=self.new_name_row)
        self.new_name_label.setObjectName("new_name_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.new_name_label)
        self.new_name_edit = QtWidgets.QLineEdit(parent=self.new_name_row)
        self.new_name_edit.setObjectName("new_name_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.new_name_edit)
        self.verticalLayout.addWidget(self.new_name_row)
        self.verticalLayout_2.addWidget(self.main_area)
        self.button_area = QtWidgets.QWidget(parent=LinkRenameDialog)
        self.button_area.setObjectName("button_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_area)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_box_ok_cancel = QtWidgets.QDialogButtonBox(parent=self.button_area)
        self.button_box_ok_cancel.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box_ok_cancel.setObjectName("button_box_ok_cancel")
        self.horizontalLayout.addWidget(self.button_box_ok_cancel)
        self.verticalLayout_2.addWidget(self.button_area)

        self.retranslateUi(LinkRenameDialog)
        self.button_box_ok_cancel.accepted.connect(LinkRenameDialog.accept) # type: ignore
        self.button_box_ok_cancel.rejected.connect(LinkRenameDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LinkRenameDialog)

    def retranslateUi(self, LinkRenameDialog):
        _translate = QtCore.QCoreApplication.translate
        LinkRenameDialog.setWindowTitle(_translate("LinkRenameDialog", "Rename Link"))
        self.current_name_label.setText(_translate("LinkRenameDialog", "Current Name:"))
        self.references_label.setText(_translate("LinkRenameDialog", "References"))
        self.new_name_label.setText(_translate("LinkRenameDialog", "New Name:"))
