# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\ui_files\status_bar_main_sim.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainSimStatus(object):
    def setupUi(self, MainSimStatus):
        MainSimStatus.setObjectName("MainSimStatus")
        MainSimStatus.resize(418, 28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainSimStatus.sizePolicy().hasHeightForWidth())
        MainSimStatus.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainSimStatus)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_sim_type = QtWidgets.QLabel(MainSimStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sim_type.setFont(font)
        self.label_sim_type.setStyleSheet("background-color:rgb(252, 252, 252)\n"
"")
        self.label_sim_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sim_type.setObjectName("label_sim_type")
        self.horizontalLayout.addWidget(self.label_sim_type)
        self.label_state = QtWidgets.QLabel(MainSimStatus)
        self.label_state.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_state.setFont(font)
        self.label_state.setObjectName("label_state")
        self.horizontalLayout.addWidget(self.label_state)
        self.label_state_value = QtWidgets.QLabel(MainSimStatus)
        self.label_state_value.setObjectName("label_state_value")
        self.horizontalLayout.addWidget(self.label_state_value)
        self.label_time = QtWidgets.QLabel(MainSimStatus)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout.addWidget(self.label_time)
        self.label_time_value = QtWidgets.QLabel(MainSimStatus)
        self.label_time_value.setObjectName("label_time_value")
        self.horizontalLayout.addWidget(self.label_time_value)
        self.label_events = QtWidgets.QLabel(MainSimStatus)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_events.setFont(font)
        self.label_events.setObjectName("label_events")
        self.horizontalLayout.addWidget(self.label_events)
        self.label_events_value = QtWidgets.QLabel(MainSimStatus)
        self.label_events_value.setObjectName("label_events_value")
        self.horizontalLayout.addWidget(self.label_events_value)
        self.label_alert = QtWidgets.QLabel(MainSimStatus)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_alert.setFont(font)
        self.label_alert.setObjectName("label_alert")
        self.horizontalLayout.addWidget(self.label_alert)
        self.label_alert_indicator = QtWidgets.QLabel(MainSimStatus)
        self.label_alert_indicator.setObjectName("label_alert_indicator")
        self.horizontalLayout.addWidget(self.label_alert_indicator)

        self.retranslateUi(MainSimStatus)
        QtCore.QMetaObject.connectSlotsByName(MainSimStatus)

    def retranslateUi(self, MainSimStatus):
        _translate = QtCore.QCoreApplication.translate
        MainSimStatus.setWindowTitle(_translate("MainSimStatus", "Form"))
        MainSimStatus.setStatusTip(_translate("MainSimStatus", "Main Sim Status"))
        self.label_sim_type.setText(_translate("MainSimStatus", " Main Sim "))
        self.label_state.setText(_translate("MainSimStatus", "State:"))
        self.label_state_value.setText(_translate("MainSimStatus", "<none>"))
        self.label_time.setText(_translate("MainSimStatus", "Time:"))
        self.label_time_value.setText(_translate("MainSimStatus", "0000 00:00:00"))
        self.label_events.setText(_translate("MainSimStatus", "Events:"))
        self.label_events_value.setText(_translate("MainSimStatus", "0"))
        self.label_alert.setText(_translate("MainSimStatus", "Alert:"))
        self.label_alert_indicator.setText(_translate("MainSimStatus", "<none>"))

