# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\origame\gui\ui_files\status_bar_batch_sim.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchSimStatusBar(object):
    def setupUi(self, BatchSimStatusBar):
        BatchSimStatusBar.setObjectName("BatchSimStatusBar")
        BatchSimStatusBar.resize(275, 28)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BatchSimStatusBar)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_sim_type = QtWidgets.QLabel(BatchSimStatusBar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sim_type.setFont(font)
        self.label_sim_type.setStyleSheet("background-color: rgb(252, 252, 252)")
        self.label_sim_type.setObjectName("label_sim_type")
        self.horizontalLayout.addWidget(self.label_sim_type)
        self.label_state = QtWidgets.QLabel(BatchSimStatusBar)
        self.label_state.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_state.setFont(font)
        self.label_state.setObjectName("label_state")
        self.horizontalLayout.addWidget(self.label_state)
        self.label_state_value = QtWidgets.QLabel(BatchSimStatusBar)
        self.label_state_value.setObjectName("label_state_value")
        self.horizontalLayout.addWidget(self.label_state_value)
        self.label_completed = QtWidgets.QLabel(BatchSimStatusBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_completed.setFont(font)
        self.label_completed.setObjectName("label_completed")
        self.horizontalLayout.addWidget(self.label_completed)
        self.label_compl_actual_value = QtWidgets.QLabel(BatchSimStatusBar)
        self.label_compl_actual_value.setObjectName("label_compl_actual_value")
        self.horizontalLayout.addWidget(self.label_compl_actual_value)
        self.label_compl_vals_sep = QtWidgets.QLabel(BatchSimStatusBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_compl_vals_sep.setFont(font)
        self.label_compl_vals_sep.setObjectName("label_compl_vals_sep")
        self.horizontalLayout.addWidget(self.label_compl_vals_sep)
        self.label_compl_total_value = QtWidgets.QLabel(BatchSimStatusBar)
        self.label_compl_total_value.setObjectName("label_compl_total_value")
        self.horizontalLayout.addWidget(self.label_compl_total_value)

        self.retranslateUi(BatchSimStatusBar)
        QtCore.QMetaObject.connectSlotsByName(BatchSimStatusBar)

    def retranslateUi(self, BatchSimStatusBar):
        _translate = QtCore.QCoreApplication.translate
        BatchSimStatusBar.setWindowTitle(_translate("BatchSimStatusBar", "Form"))
        self.label_sim_type.setText(_translate("BatchSimStatusBar", " Batch Sim "))
        self.label_state.setText(_translate("BatchSimStatusBar", "State:"))
        self.label_state_value.setText(_translate("BatchSimStatusBar", "<none>"))
        self.label_completed.setText(_translate("BatchSimStatusBar", "Completed:"))
        self.label_compl_actual_value.setText(_translate("BatchSimStatusBar", "0"))
        self.label_compl_vals_sep.setText(_translate("BatchSimStatusBar", "/"))
        self.label_compl_total_value.setText(_translate("BatchSimStatusBar", "0"))

